// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Synerixis.Infrastructure.Data;

#nullable disable

namespace Synerixis.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202172424_InitialCreateWithLowerCaseTables")]
    partial class InitialCreateWithLowerCaseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Synerixis.Domain.Entities.Brand", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Category", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("binary(16)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ConversationId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("DataJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFromUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Conversation", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastViewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("SellerId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.PayOrder", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OutTradeNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("SellerId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("PayOrders");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Product", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("BrandId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("CategoryId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VideosJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.ProductAttribute", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsKey")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSale")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ParentId")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("ProductId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttribute");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.SKU", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<byte[]>("ProductId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("SpecsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("SKUs");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Seller", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int?>("FreeQuota")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastLoginType")
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("RegisterSource")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SubscriptionEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubscriptionLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OpenId")
                        .IsUnique();

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.SellerConfig", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultReplyTone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EnableAutoMarketingReminder")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MainCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MemoryRetentionDays")
                        .HasColumnType("int");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("SellerId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ShopLogo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TargetCustomerDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SellerId")
                        .IsUnique();

                    b.ToTable("SellerConfigs");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.SellerProduct", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<decimal?>("CustomPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("CustomStock")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OptimizedDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OptimizedTagsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OptimizedTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ProductId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("SellerId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("SellerProducts");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Synerixis.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Synerixis.Domain.Entities.Seller", "Seller")
                        .WithMany("Conversations")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.PayOrder", b =>
                {
                    b.HasOne("Synerixis.Domain.Entities.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Product", b =>
                {
                    b.HasOne("Synerixis.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Synerixis.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.ProductAttribute", b =>
                {
                    b.HasOne("Synerixis.Domain.Entities.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.SKU", b =>
                {
                    b.HasOne("Synerixis.Domain.Entities.Product", "Product")
                        .WithMany("SKUs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.SellerConfig", b =>
                {
                    b.HasOne("Synerixis.Domain.Entities.Seller", "Seller")
                        .WithOne("Config")
                        .HasForeignKey("Synerixis.Domain.Entities.SellerConfig", "SellerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.SellerProduct", b =>
                {
                    b.HasOne("Synerixis.Domain.Entities.Product", "Product")
                        .WithMany("SellerProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Synerixis.Domain.Entities.Seller", "Seller")
                        .WithMany("SellerProducts")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("SKUs");

                    b.Navigation("SellerProducts");
                });

            modelBuilder.Entity("Synerixis.Domain.Entities.Seller", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("Conversations");

                    b.Navigation("SellerProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
